name = "han-analytics"
compatibility_date = "2024-09-21"
pages_build_output_dir = "dist"

[[analytics_engine_datasets]]
binding = "AnalyticsBinding"
dataset = "AnalyticsDataset"
[vars]
CLOUDFLARE_ACCOUNT_ID = 'b600495c26b25549e73f6bb9eadb46fe'
CLOUDFLARE_API_TOKEN = 'tYKB_htkb767wRBN-A-sXwNE6cEA-XCl9SWeW4KA'
# 网站访问密码 (不设置即无需密码访问)
CLOUDFLARE_WEBSITE_PWD = ''
# 可统计的白名单 格式：  域名,WebSite|域名,WebSite，多个站点使用|分隔 例如：'api.vvhan.com,Hello-Han-Api|www.vvhan.com,Hello-HanHexoBlog'  (不设置即允许任何统计)
CLOUDFLARE_WEBSITE_WHITELIST = 'fx.baoge666.us.kg,hananalytics|am.baoge666.us.kg,am'
